### Test the home page endpoint

GET http://localhost:3001/logos

### Test creating a logo after you build the code for adding a logo
POST http://localhost:3001/logos
Content-Type: application/json

{
  "name": "Waldo"
}

### Test the PUT which should change a logo
PUT http://localhost:3001/logos/
Content-Type: application/json

{
  "name": "Where's the Ball",
  "color": "Red"
}

### Test Delete
DELETE http://localhost:3001/logos/5f2c931f97989f2a807c45c5
Content-Type: application/json